services:
  app:
    build: .
    container_name: python_dev
    volumes:
      - .:/usr/src/app
    # ports:
    #   - "5000:5000"  # Expose Flask or any web app on port 5000
    command: ["tail", "-f", "/dev/null"]  # Keep the container running
